version: '3'
services:
  postgres-cadastro:
    container_name: postgres-cadastro
    image: postgres:12.2
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432"

  mssql:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password!23
      - MSSQL_PID=Developer
  mssqlscripts:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - mssql
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "Password!23" -Q "create database Keycloak"; do sleep 5; done'
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    depends_on:
      - mssql
      - mssqlscripts
    ports:
      - "8180:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mssql
      - DB_USER=sa
      - DB_PASSWORD=Password!23
      - DB_ADDR=mssql
      - DB_DATABASE=Keycloak

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.21.0
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"