"%local":
  mp:
    jwt:
      verify:
        issuer: http://localhost:8180/auth/realms/ifood #Endereço do nosso realm, em quem confiamos para criar o token
        #Chave publica do healm, da para pegar acessando o link do healm
        publickey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl7N3wbtv7ta7B8FfXVkAigAj1vPX3LE/v87MPNgMqtC3AEwxKGpyfODuQJhntyQCrNQ34BiJ0GTv/1Aygl0MKK1e5xSgOjFmtPVBcOZFH9rE35Yh+E6/HkIyUyber0+zAaRZ0Nq4f31wNrd3nt9Rm9LLjl/C/mEXsY4igbjt85nGostbeQuZ6DMseKrW4laPe/6AB47Mz1KuHYGfTAvZa2juPCw/nqHYFehGpVT9+W/GJgbVig9kyg+y99IqgvzT/7znPclkxPB89BpaR1yNuZ2MdevZcmUdwLBGu22vH5NV4f/cHDXk4tqZFouYsV2M9Gb7LA4yJkoG5qUhB6/UUwIDAQAB

  quarkus:
    log: # ALL > FINEST > FINER > FINE > CONFIG > INFO > WARNING > SEVERE > OFF
      console:
        async: true
        color: true
        enable: true
        format: "%d{yyyy-MM-dd HH:mm:ss,SSS} |- %-5p in %c:%L{3.} [%t] - %s%e%n"
      level: WARNING

    resteasy:
      path: /api
#      role:
#        based:
#          security: true

    http:
      port: 8081

    datasource:
      db-kind: postgresql
      username: cadastro
      password: cadastro
      jdbc:
        url: jdbc:postgresql://localhost:5432/postgres

    hibernate-orm:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      database:
        generation: drop-and-create

    swagger-ui:
      always-include: true #Para deixar habilitado o swagger em producao (quando gerar o jar).
      path: /swagger

"%dev":
  teste:
    valor: wallace-dev
  quarkus:
    http:
      port: 8081
    datasource:
      db-kind: postgresql
      username: cadastro
      password: cadastro
      jdbc:
        url: jdbc:postgresql://localhost:5432/postgres

    hibernate-orm:
      database:
        generation: drop-and-create

    swagger-ui:
      always-include: true
      path: /test-swagger



"%prod":
  teste:
    valor: wallace-local
  quarkus:
    http:
      port: 8081
    datasource:
      db-kind: postgresql
      username: cadastro
      password: cadastro
      jdbc:
        url: jdbc:postgresql://localhost:5432/postgres

    hibernate-orm:
      database:
        generation: drop-and-create

    swagger-ui:
      always-include: true
      path: /test-swagger